import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from './components/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Board - Organizando suas tarefas.</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <main className={styles.contentContainer}>
        <img src="./images/board-user.svg" alt="Ferramento board" width={400} />
        <section className={styles.callToAction}>
          <h1>Uma ferramente para seu dia a dia escreva, planeje e organize-se.</h1>
          <p>
            <span>100% gratuita</span>
            e online.
          </p>
        </section>
        <div className={styles.donaters}>
          <img src="https://sujeitoprogramador.com/steve.png" alt="Foto apoiador" />
        </div>
      </main>

    </div>
  )
}

export default Home
